
import { AppWrapper } from "../front-extras/helpers/Context";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppWrapper>
      <html lang="en">
      <body className={""}>
        {children}

      </body>
    </html>
  </AppWrapper>
    
  );
}
