
import { AppWrapper } from "../front-extras/helpers/Context";
import "./globals.scss";

export const metadata = {
  title: "MicelIA",
  description: "Generated by create next app",
  icons: "/logo.ico",
  manifest: "/manifest.json", //PWA
};

export default function RootLayout({ children }) {
  return (
    <AppWrapper>
      <html lang="en">
      <body className="container">
        {children}

      </body>
    </html>
  </AppWrapper>
    
  );
}
